# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8.17
      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.5.1
      - name: Configure Poetry
        shell: bash
        run: python -m poetry config virtualenvs.in-project true
      - name: View poetry version
        run: poetry --version
      - name: Install Dependencies
        run: |
          python -m poetry install

  Release:
    needs: Quality
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8.17
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.5.1
      - name: Build Frontend
        working-directory: ./streamlit_calendar/frontend
        run: |
          npm install
          npm run build
      - name: Set Release
        run: sed -i 's/_RELEASE = False/_RELEASE = True/g' ./streamlit_calendar/__init__.py
      - name: Semantic Release
        uses: bjoluc/semantic-release-config-poetry@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          RELEASE_BRANCH: master
